### ISSUE TITLE
No aparecen mis avances

### ISSUE THREAD

**Issue by Anecarat** [AliciaMstt/BioinfInvRepro2017-II#105]
Estoy checando que no se reflejaron mis avances. El archivo lo subí el viernes como quedamos y me aseguré de que se reflejara en el documento, hice el commit y el pull request. De todas formas, mis avances los tengo desde el 25 de abril y la fecha se ve reflejada en mi repositorio. 

Voy a volver a hacer el pull request. 

Saludos.

**Comment by AliciaMstt** [comment]
Apenas llegó el pull request hace 9 hrs. Ojo.

Update Listado_Proyectos_finales.md
#107 opened 9 hours ago by Anecarat
