### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [AliciaMstt/BioinfInvRepro2017-II#98]
Cuida tu md, sale la mayor parte del texto en negritas y no estoy segura que esto lo hayas hecho a proósito. 

Sobre tus dudas:

*No entiendo que es y para que es -b (batch_id)*

Sirve para identificar diferentes corridas con pruebas distintas, puedes dejarlo en 1.

*Aun no me queda claro en que momento cargas la base de datos con los SNP's y en que formato deben ir estos.*

La base de datos de SNPs tienes que generarla con el propio Stacks. populations es un programa downstream que asume que ya corriste todo lo demás, es decir denovo_map.pl (de novo ) o ref_map.pl (si tienes genoma de referencia).

Instalar Stacks NO ES TRIVIAL, por lo que si no lo has hecho ya, apúrale y córrelo con los datos de prueba para garantizar que funcione.

**Comment by andyrh0402** [comment]
Hola Alicia, creo que esos cometarios no son para mi...

**Comment by AliciaMstt** [comment]
Efectivamente....
